### ISSUE TITLE
Can't run predictor

### ISSUE THREAD

**Issue by theyamo** [jawline/Synthic#1]
Fails on Python 3.10. Could be that adaptive warmup is not in version control?
```
Traceback (most recent call last):
  File "/Users/yamo/src/Synthic/predictor/src/Predictor.py", line 20, in <module>
    from model import load_gameboy_net
  File "/Users/yamo/src/Synthic/predictor/src/model.py", line 14, in <module>
    from adaptive_warmup import Scheduler as AdaptiveWarmup
ModuleNotFoundError: No module named 'adaptive_warmup'```

**Comment by theyamo** [comment]
Never mind, found out it's because of the uninstalled package.
